name: build-test-deploy

on: push

jobs: 
  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: checkout repo 
        uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with: 
          # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
          path: ~/.npm
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
  # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: use node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18.x'
      - run: npm install
      - run: npm run build
      
  test:
     needs: build
     
     runs-on: ubuntu-latest
     
     steps:
       - name: checkout repo
         uses: actions/checkout@v3
       - name: use node.js
         uses: actions/setup-node@v3
         with: 
           node-version: '18.x'
       - run: npm install
       - run: npm test
